= Prise en charge des datastores VMware VMFS sur site et sur site
:allow-uri-read: 




=== Prise en charge des datastores VMware VMFS sur site et sur site

Cette version inclut la prise en charge des machines virtuelles montées sur des datastores VMFS (Virtual machine File System) VMware vSphere pour iSCSI et FC protégées sur le stockage sur site. Auparavant, le service fournissait un _aperçu de la technologie_ prenant en charge les datastores VMFS pour iSCSI et FC.

Voici quelques considérations supplémentaires concernant à la fois les protocoles iSCSI et FC :

* La prise en charge de FC concerne les protocoles client frontaux, pas la réplication.
* La reprise d'activité BlueXP  ne prend en charge qu'une seule LUN par volume ONTAP. Le volume ne doit pas avoir plusieurs LUN.
* Pour tout plan de réplication, le volume ONTAP de destination doit utiliser les mêmes protocoles que le volume ONTAP source hébergeant les VM protégées. Par exemple, si la source utilise un protocole FC, la destination doit également utiliser FC.

