= Découverte planifiée pour les VM
:allow-uri-read: 




=== Découverte planifiée pour les VM

La reprise sur incident BlueXP  effectue une détection toutes les 24 heures. Avec cette version, vous pouvez désormais personnaliser le calendrier de découverte pour répondre à vos besoins et réduire l'impact sur les performances lorsque vous en avez besoin. Par exemple, si vous disposez d'un grand nombre de machines virtuelles, vous pouvez définir la planification de la découverte pour qu'elle s'exécute toutes les 48 heures. Si vous disposez d'un petit nombre de machines virtuelles, vous pouvez définir la planification de découverte pour qu'elle s'exécute toutes les 12 heures.

Si vous ne souhaitez pas que wan planifie la découverte, vous pouvez désactiver l'option de découverte planifiée et actualiser la découverte manuellement à tout moment.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Ajoutez des sites de serveur vCenter"] .



=== Prise en charge des datastores de groupes de ressources

Auparavant, vous ne pouviez créer des groupes de ressources que par des machines virtuelles. Avec cette version, vous pouvez créer un groupe de ressources par datastores. Lorsque vous créez un plan de réplication et un groupe de ressources pour ce plan, toutes les machines virtuelles d'un datastore sont répertoriées. Cette option est utile si vous disposez d'un grand nombre de machines virtuelles et que vous souhaitez les regrouper par datastore.

Vous pouvez créer un groupe de ressources avec un datastore de l'une des manières suivantes :

* Lorsque vous ajoutez un groupe de ressources à l'aide de datastores, vous pouvez voir la liste des datastores. Vous pouvez sélectionner un ou plusieurs datastores pour créer un groupe de ressources.
* Lorsque vous créez un plan de réplication et un groupe de ressources dans le plan, vous pouvez voir les machines virtuelles dans les datastores.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Notifications d'expiration de licence ou d'essai gratuit

Cette version fournit des notifications indiquant que l'essai gratuit expirera dans 60 jours pour vous assurer que vous avez le temps d'obtenir une licence. Cette version fournit également des notifications le jour de l'expiration de la licence.



=== Notification des mises à jour de service

Avec cette version, une bannière s'affiche en haut pour indiquer que les services sont en cours de mise à niveau et que le service est placé en mode de maintenance. La bannière s'affiche lorsque le service est mis à niveau et disparaît lorsque la mise à niveau est terminée. Bien que vous puissiez continuer à travailler dans l'interface utilisateur pendant la mise à niveau, vous ne pouvez pas soumettre de nouveaux travaux. Les tâches planifiées s'exécuteront une fois la mise à jour terminée et le service retournera en mode de production.
