= Rôles des utilisateurs dans la BlueXP disaster recovery
:allow-uri-read: 




=== Rôles des utilisateurs dans la BlueXP disaster recovery

La BlueXP disaster recovery utilise désormais des rôles pour gérer l’accès de chaque utilisateur à des fonctionnalités et actions spécifiques.

Le service utilise les rôles suivants qui sont spécifiques à la BlueXP disaster recovery.

* *Administrateur de récupération après sinistre* : effectuez toutes les actions dans la BlueXP disaster recovery.
* *Administrateur de basculement de reprise après sinistre* : effectuez des actions de basculement et de migration dans la BlueXP disaster recovery.
* *Administrateur d'application de récupération après sinistre* : Créez et modifiez des plans de réplication et démarrez des tests de basculement.
* *Visionneuse de récupération après sinistre* : affichez les informations dans la BlueXP disaster recovery, mais ne pouvez effectuer aucune action.


Si vous cliquez sur le service de BlueXP disaster recovery et le configurez pour la première fois, vous devez disposer de l'autorisation *SnapCenterAdmin* ou du rôle *Administrateur d'organisation*.

Pour plus de détails, voir  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Rôles et autorisations des utilisateurs dans la BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].



=== Autres mises à jour de la BlueXP disaster recovery

* Découverte de réseau améliorée
* Améliorations de l'évolutivité :
+
** Filtrage des métadonnées requises au lieu de tous les détails
** Améliorations de la découverte pour récupérer et mettre à jour les ressources des machines virtuelles plus rapidement
** Optimisation de la mémoire et des performances pour la récupération et la mise à jour des données
** Améliorations de la création de clients vCenter SDK et de la gestion des pools


* Gestion des données obsolètes lors de la prochaine découverte planifiée ou manuelle :
+
** Lorsqu'une machine virtuelle est supprimée dans vCenter, la BlueXP disaster recovery la supprime désormais automatiquement du plan de réplication.
** Lorsqu'une banque de données ou un réseau est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.
** Lorsqu'un cluster, un hôte ou un centre de données est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.


* Vous pouvez désormais accéder à la documentation Swagger en mode navigation privée. Vous pouvez y accéder depuis la BlueXP disaster recovery via Paramètres > Documentation API ou directement à l'URL suivante en mode navigation privée :  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentation Swagger"^] .
* Dans certains cas, après une restauration automatique, l'iGroup était conservé une fois l'opération terminée. Cette mise à jour supprime l'iGroup s'il est obsolète.
* Si le nom de domaine complet NFS était utilisé dans le plan de réplication, la BlueXP disaster recovery le résout désormais en adresse IP. Cette mise à jour est utile si le nom de domaine complet n'est pas résoluble sur le site de reprise après sinistre.
* Améliorations de l'alignement de l'interface utilisateur
* Améliorations du journal pour capturer les détails de dimensionnement de vCenter après la découverte réussie

