= Mappage de sous-réseau
:allow-uri-read: 




=== Mappage de sous-réseau

Avec cette version, vous pouvez gérer les adresses IP en cas de basculement de manière nouvelle à l'aide du mappage de sous-réseau, qui vous permet d'ajouter des sous-réseaux pour chaque vCenter. Dans ce cas, vous définissez le CIDR IPv4, la passerelle par défaut et le DNS pour chaque réseau virtuel.

Lors du basculement, la reprise après incident BlueXP  détermine l'adresse IP appropriée de chaque vNIC en examinant le CIDR fourni pour le réseau virtuel mappé et l'utilise pour dériver la nouvelle adresse IP.

Par exemple :

* Réseau a = 10.1.1.0/24
* Réseau B = 192.168.1.0/24


VM1 dispose d'une vNIC (10.1.1.50) connectée au réseau A. NetworkA est mappé sur le réseau B dans les paramètres du plan de réplication.

En cas de basculement, la reprise après incident BlueXP  remplace la partie réseau de l'adresse IP d'origine (10.1.1) et conserve l'adresse hôte (.50) de l'adresse IP d'origine (10.1.1.50). Pour VM1, BlueXP  Disaster Recovery examine les paramètres CIDR du réseau B et utilise cette partie du réseau 192.168.1 tout en conservant la partie hôte (.50) pour créer la nouvelle adresse IP du VM1. La nouvelle adresse IP devient 192.168.1.50.

En résumé, l'adresse de l'hôte reste la même, tandis que l'adresse réseau est remplacée par celle configurée dans le mappage de sous-réseau du site. Cela vous permet de gérer plus facilement la réaffectation d'adresses IP en cas de basculement, notamment si vous avez des centaines de réseaux et des milliers de machines virtuelles à gérer.

Pour plus d'informations sur l'inclusion du mappage de sous-réseau dans vos sites, reportez-vous à la section link:../use/sites-add.html["Ajoutez des sites de serveur vCenter"].



=== Ignorer la protection

Vous pouvez maintenant ignorer la protection afin que le service ne crée pas automatiquement une relation de protection inverse après un basculement de plan de réplication. Cette fonction est utile si vous souhaitez effectuer des opérations supplémentaires sur le site restauré avant de le remettre en ligne dans le cadre de la reprise sur incident BlueXP .

Lorsque vous initiez un basculement, par défaut, le service crée automatiquement une relation de protection inverse pour chaque volume du plan de réplication, si le site source d'origine est en ligne. Cela signifie que le service crée une relation SnapMirror entre le site cible et le site source. Par ailleurs, le service inverse automatiquement la relation SnapMirror lorsque vous initiez un retour arrière.

Lorsque vous lancez un basculement, vous pouvez maintenant choisir une option *Ignorer la protection*. Avec cela, le service n'inverse pas automatiquement la relation SnapMirror. Il laisse le volume inscriptible des deux côtés du plan de réplication.

Une fois le site source d'origine remis en ligne, vous pouvez établir une protection inverse en sélectionnant *protéger les ressources* dans le menu actions du plan de réplication. Cette opération tente de créer une relation de réplication inverse pour chaque volume du plan. Vous pouvez exécuter cette tâche plusieurs fois jusqu'à ce que la protection soit restaurée. Une fois la protection restaurée, vous pouvez lancer un rétablissement de la manière habituelle.

Pour plus d'informations sur le saut de protection, voir link:../use/failover.html["Basculement des applications vers un site distant"].



=== SnapMirror planifie les mises à jour dans le plan de réplication

La reprise sur incident BlueXP  prend désormais en charge l'utilisation de solutions de gestion externe des snapshots, comme le planificateur de règles ONTAP SnapMirror natif ou les intégrations tierces avec ONTAP. Si chaque datastore (volume) du plan de réplication dispose déjà d'une relation SnapMirror gérée par un autre emplacement, vous pouvez utiliser ces snapshots comme points de restauration dans la reprise d'activité BlueXP .

Pour configurer, dans la section Replication Plan > Resource Mapping, cochez la case *utiliser les sauvegardes gérées par la plate-forme et les plannings de rétention* lors de la configuration du mappage des datastores.

Lorsque cette option est sélectionnée, la reprise sur incident BlueXP  ne configure pas de programme de sauvegarde. Toutefois, vous devez toujours configurer un planning de conservation, car les snapshots peuvent toujours être créés pour les opérations de test, de basculement et de restauration.

Une fois configuré, le service ne prend pas de snapshots planifiés régulièrement, mais s'appuie plutôt sur l'entité externe pour prendre et mettre à jour ces snapshots.

Pour plus de détails sur l'utilisation de solutions d'instantanés externes dans le plan de réplication, reportez-vous à la section link:../use/drplan-create.html["Créer un plan de réplication"].
