---
sidebar: sidebar 
permalink: reference/dr-reference-roles.html 
keywords: how bluexp disaster recovery works, what is disaster recovery, bluexp, vmware, vcenter, draas, replicate, failover, failback, fail over, fail back, vmware cloud, netapp intelligent services 
summary: 'La BlueXP disaster recovery utilise des rôles pour gérer l"accès de chaque utilisateur à des fonctionnalités et actions spécifiques.' 
---
= Accès aux fonctionnalités de BlueXP disaster recovery basé sur les rôles
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La BlueXP disaster recovery utilise des rôles pour gérer l'accès de chaque utilisateur à des fonctionnalités et actions spécifiques.

Le service utilise les rôles suivants qui sont spécifiques à la BlueXP disaster recovery.

* *Administrateur de récupération après sinistre* : effectuez toutes les actions dans la BlueXP disaster recovery.
* *Administrateur de basculement de reprise après sinistre* : effectuez des actions de basculement et de migration dans la BlueXP disaster recovery.
* *Administrateur d'application de récupération après sinistre* : Créez et modifiez des plans de réplication et démarrez des tests de basculement.
* *Visionneuse de récupération après sinistre* : affichez les informations dans la BlueXP disaster recovery, mais ne pouvez effectuer aucune action.


Ces rôles sont spécifiques à la BlueXP disaster recovery et ne sont pas les mêmes que les rôles de plate-forme utilisés dans BlueXP. Pour plus de détails sur tous les rôles de plate-forme BlueXP , voir https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Documentation d'installation et d'administration de BlueXP"^].

Le tableau suivant indique les actions que chaque rôle de BlueXP disaster recovery peut effectuer.

[cols="30,20a,20a,20a,20a"]
|===
| Fonction et action | Administrateur de reprise après sinistre | Administrateur de basculement de reprise après sinistre | Administrateur d'application de reprise après sinistre | Visionneuse de reprise après sinistre 


| Afficher le tableau de bord et tous les onglets  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Essayer gratuitement  a| 
Oui
 a| 
Non
 a| 
Non
 a| 
Non



| Lancez la découverte des charges de travail  a| 
Oui
 a| 
Non
 a| 
Non
 a| 
Non



| Afficher les informations de licence  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Activer la licence  a| 
Oui
 a| 
Non
 a| 
Oui
 a| 
Non



5+| *Dans l'onglet Sites* : 


| Voir les sites  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Ajouter, modifier ou supprimer des sites  a| 
Oui
 a| 
Non
 a| 
Non
 a| 
Non



5+| *Dans l'onglet Plans de réplication* : 


| Afficher les plans de réplication  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Afficher les détails du plan de réplication  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Créer ou modifier des plans de réplication  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Non



| Créer des rapports  a| 
Oui
 a| 
Non
 a| 
Non
 a| 
Non



| Voir les instantanés  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Effectuer des tests de basculement  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Non



| Effectuer des basculements  a| 
Oui
 a| 
Oui
 a| 
Non
 a| 
Non



| Effectuer des restaurations automatiques  a| 
Oui
 a| 
Oui
 a| 
Non
 a| 
Non



| Effectuer des migrations  a| 
Oui
 a| 
Oui
 a| 
Non
 a| 
Non



5+| *Dans l'onglet Groupes de ressources* : 


| Afficher les groupes de ressources  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Oui



| Créer, modifier ou supprimer des groupes de ressources  a| 
Oui
 a| 
Non
 a| 
Oui
 a| 
Non



5+| *Dans l'onglet Suivi des tâches* : 


| Afficher les travaux  a| 
Oui
 a| 
Non
 a| 
Oui
 a| 
Oui



| Annuler les emplois  a| 
Oui
 a| 
Oui
 a| 
Oui
 a| 
Non

|===