---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-closing.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 'Introduction à la reprise après sinistre BlueXP à l"aide d"Amazon EVS et d"Amazon FSxN.' 
---
= Conclusion
:allow-uri-read: 


[role="lead"]
La solution de reprise après sinistre BlueXP offre une solution de reprise après sinistre cloud hybride et économique pour votre infrastructure VMware sur site, configurée pour utiliser Amazon EVS et Amazon FSx for NetApp ONTAP comme cible de reprise après sinistre. Vous disposez ainsi d'une cible de reprise après sinistre robuste pour vos infrastructures critiques. La solution de reprise après sinistre BlueXP s'appuie sur les fonctionnalités natives de protection des données ONTAP, fruit de décennies d'expérience et de tests approfondis, pour garantir une protection optimale de vos données.

Pour plus d'informations :

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Mise en route avec Amazon FSX pour NetApp ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Documentation sur la reprise après sinistre de NetApp BlueXP"]

