---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Une fois le connecteur BlueXP installé, vous devez intégrer toutes les ressources de stockage ONTAP et VMware vCenter qui participeront au processus de reprise après sinistre. 
---
= Présentation de la configuration de la reprise après sinistre BlueXP pour Amazon EVS
:allow-uri-read: 


[role="lead"]
Après avoir installé le connecteur BlueXP, vous devez intégrer toutes les ressources de stockage ONTAP et VMware vCenter qui participeront au processus de récupération après sinistre avec la récupération après sinistre BlueXP.

* link:evs-deploy-guide-config-prereqs.html["Conditions préalables pour la reprise après sinistre Amazon EVS avec BlueXP"]
* link:evs-deploy-guide-config-add-arrays.html["Ajoutez des baies de stockage ONTAP à la reprise après sinistre BlueXP"]
* link:evs-deploy-guide-enable-draas.html["Activer la reprise après sinistre BlueXP pour Amazon EVS"]
* link:evs-deploy-guide-config-add-arrays.html["Ajouter des sites vCenter à la récupération après sinistre BlueXP"]
* link:evs-deploy-guide-add-vcenters.html["Ajouter des clusters vCenter à la reprise après sinistre BlueXP"]

