---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: NetApp BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. Vous pouvez surveiller toutes les tâches de reprise sur incident et déterminer leur progression. 
---
= Surveiller les tâches de récupération après sinistre BlueX
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Vous pouvez surveiller toutes les tâches de récupération après sinistre BlueXP et déterminer leur progression.



== Afficher les travaux

*Rôle BlueXP requis* Administrateur d'organisation, administrateur de dossier ou de projet, administrateur de récupération après sinistre, administrateur d'application de récupération après sinistre ou rôle de visualiseur de récupération après sinistre.

link:../reference/dr-reference-roles.html["En savoir plus sur les rôles et les autorisations des utilisateurs dans la BlueXP disaster recovery"]. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].

.Étapes
. Dans le menu de navigation gauche de BlueXP, sélectionnez *protection* > *reprise après sinistre*.
. Dans le menu supérieur, sélectionnez *surveillance des travaux*.
. Explorez tous les travaux liés aux opérations et vérifiez leurs horodatages et leur état.
. Pour afficher les détails d'un travail particulier, sélectionnez cette ligne.
. Pour actualiser les informations, sélectionnez *Actualiser*.




== Annuler un travail

Si un travail est en cours ou en file d'attente et que vous ne souhaitez pas qu'il continue, vous pouvez l'annuler. Vous pouvez annuler un travail s'il est bloqué dans le même état et que vous souhaitez libérer l'opération suivante dans la file d'attente. Vous pouvez annuler un travail avant qu'il ne soit trop tard.

*Rôle BlueXP requis* Administrateur d'organisation, administrateur de dossier ou de projet, administrateur de récupération après sinistre, administrateur de basculement de récupération après sinistre ou administrateur d'application de récupération après sinistre.

link:../reference/dr-reference-roles.html["En savoir plus sur les rôles et les autorisations des utilisateurs dans la BlueXP disaster recovery"]. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].

.Étapes
. Dans le menu de navigation gauche de BlueXP, sélectionnez *protection* > *reprise après sinistre*.
. Dans le menu supérieur, sélectionnez *surveillance des travaux*.
. Sur la page moniteur de travaux, notez l'ID du travail que vous souhaitez annuler.
+
Le travail doit être à l'état « en cours » ou « en file d'attente ».

. Dans la colonne actions, sélectionnez *Annuler le travail*.

