---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: 'La révision de rapports de reprise sur incident peut vous aider à analyser votre niveau de préparation à la reprise sur incident. Les rapports préconçus incluent un récapitulatif des basculements et des basculements, des détails de réplication sur tous les sites et des détails des tâches pour l"année écoulée.' 
---
= Créer des rapports de reprise après sinistre BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
L’examen des rapports de reprise après sinistre BlueXP peut vous aider à analyser votre état de préparation à la reprise après sinistre. Les rapports préconçus incluent un récapitulatif des basculements de test, des détails du plan de réplication et des détails des tâches sur tous les sites d'un compte au cours des sept derniers jours.

Vous pouvez télécharger des rapports au format PDF, HTML ou JSON.

Le lien Télécharger est valide pendant six heures.

.Étapes
. Dans la navigation de gauche de BlueXP , sélectionnez *protection* > *récupération après sinistre* > *plans de réplication*.
. En haut de la page, sélectionnez *Créer un rapport*.
. Sélectionnez le type de format de fichier et la période comprise dans les 7 derniers jours.
. Sélectionnez *Créer*.
+

NOTE: L'affichage du rapport peut prendre quelques minutes.

. Pour télécharger un rapport, sélectionnez *Télécharger le rapport* et sélectionnez-le dans le dossier Télécharger de l'administrateur.

