---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites, bluexp disaster recovery 
summary: 'Avant d"utiliser la reprise d"activité BlueXP, vérifiez que votre environnement répond aux exigences de stockage ONTAP, de cluster VMware vCenter et de BlueXP.' 
---
= Conditions préalables à la reprise d'activité BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Avant d'utiliser la reprise d'activité BlueXP, vérifiez que votre environnement répond aux exigences de stockage ONTAP, de cluster VMware vCenter et de BlueXP.



== Conditions préalables au stockage ONTAP

Ces prérequis s'appliquent aux instances ONTAP ou Amazon FSX pour NetApp ONTAP.

* Les clusters source et cible doivent avoir une relation de pairs.
* Le SVM qui hébergera les volumes de reprise d'activité doit exister sur le cluster destination.
* Le SVM source et le SVM destination doivent avoir une relation entre pairs.
+

NOTE: La création des volumes de reprise d'activité dans le SVM ou SVM de destination n'est pas anticipée. La reprise d'activité BlueXP crée les volumes de destination selon les besoins du plan de réplication.

* En cas de déploiement avec Amazon FSX pour NetApp ONTAP, la condition préalable suivante s'applique :
+
** Une instance Amazon FSX pour NetApp ONTAP pour héberger les datastores VMware DR doit exister dans votre VPC. Reportez-vous à la documentation d'Amazon FSX pour ONTAP sur https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["guide d'utilisation"^].






== Prérequis pour les clusters VMware vCenter

Ces conditions préalables s'appliquent à la fois aux clusters vCenter sur site et au Software-Defined Data Center (SDDC) de VMware Cloud for AWS.

* Tous les clusters VMware que vous souhaitez gérer avec BlueXP Disaster Recovery doivent être hébergés sur des volumes ONTAP.
* Tous les datastores VMware à gérer par la reprise d'activité BlueXP doivent utiliser l'un des protocoles suivants :
+
** NFS
** VMFS utilisant le protocole iSCSI (actuellement dans un aperçu technologique)


* Si vous utilisez un SDDC de VMware Cloud, les conditions préalables suivantes s'appliquent.
+
** Dans VMware Cloud Console, utilisez les rôles de service Administrateur et Administrateur Cloud NSX. Utilisez également le propriétaire de l'organisation pour le rôle Organisation. Reportez-vous à la https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Utilisation de la documentation VMware Cloud Foundations avec AWS FSX for NetApp ONTAP"^].
** Associez le SDDC dans le cloud VMware à l'instance Amazon FSX pour NetApp ONTAP. Reportez-vous à la https://vmc.techzone.vmware.com/fsx-guide#overview["Intégration de VMware Cloud on AWS avec Amazon FSX for NetApp ONTAP"^].






== Prérequis de BlueXP



=== Lancez-vous avec BlueXP

Si vous ne l'avez pas déjà fait, https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["Inscrivez-vous à BlueXP  et créez une entreprise"^]



=== Collectez les informations d'identification pour ONTAP et VMware

* Les identifiants Amazon FSX pour ONTAP et AWS doivent être ajoutés à l'environnement de travail dans le projet BlueXP  qui sera utilisé pour gérer la reprise d'activité BlueXP .
* La reprise d'activité BlueXP nécessite des informations d'identification vCenter. Vous entrez les informations d'identification vCenter lorsque vous ajoutez un site dans le cadre de la reprise d'activité BlueXP.
+
Pour obtenir la liste des privilèges vCenter nécessaires, reportez-vous link:../reference/vcenter-privileges.html["Privilèges vCenter requis pour la reprise d'activité BlueXP"]à la section . Pour obtenir des instructions sur l'ajout d'un site, reportez-vous à la section link:../use/sites-add.html["Ajouter un site"].





=== Créer un connecteur BlueXP

Un connecteur BlueXP doit être configuré dans BlueXP. Lorsque vous utilisez le connecteur BlueXP, il inclut les fonctionnalités appropriées pour le service de reprise d'activité.

* La reprise d'activité BlueXP fonctionne uniquement avec le déploiement de connecteur de mode standard. Voir https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Mise en route de BlueXP en mode standard"^].
* Type de connecteur BlueXP requis :
+
** *Reprise d'activité sur site et sur site* : installez le connecteur sur site BlueXP sur le site de reprise d'activité. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installez et configurez un connecteur sur site"^].
** *Sur site vers AWS* : installez le connecteur BlueXP pour AWS dans votre VPC AWS. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["Options d'installation des connecteurs dans AWS"^].
+

TIP: Du site aux environnements sur site, utilisez le connecteur sur site BlueXP. Pour les environnements sur site ou AWS, utilisez le connecteur BlueXP AWS Connector, qui permet d'accéder au vCenter sur site source et au vCenter sur site de destination.

** Le connecteur BlueXP installé doit pouvoir accéder à tout cluster VMware que la reprise d'activité BlueXP va gérer.


* Toutes les baies ONTAP devant être gérées par BlueXP  Disaster Recovery doivent être ajoutées à tout environnement de travail du projet BlueXP  qui sera utilisé pour gérer BlueXP  Disaster Recovery.
+
Voir https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Découvrez les clusters ONTAP sur site"^].





== Prérequis des charges de travail

Pour garantir la cohérence des processus au niveau des applications, appliquez les conditions préalables suivantes :

* Assurez-vous que les outils VMware (ou les outils Open VM) sont en cours d'exécution sur les machines virtuelles qui seront protégées.
* Pour les machines virtuelles Windows exécutant Microsoft SQL Server ou Oracle Database ou les deux, leurs enregistreurs VSS doivent être activés pour les bases de données.
* L'authentification utilisateur du système d'exploitation doit être activée pour le rôle SYSDBA de la base de données Oracle pour les bases de données Oracle qui s'exécutent sur un système d'exploitation Linux.

