---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: 'Pour configurer la reprise d"activité BlueXP, effectuez quelques étapes.' 
---
= Configurez votre infrastructure pour la reprise d'activité BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour utiliser la reprise d'activité BlueXP, effectuez quelques étapes de configuration dans Amazon Web Services (AWS) et BlueXP.


TIP: Révision link:../get-started/dr-prerequisites.html["prérequis"] pour vous assurer que votre environnement est prêt.



== Préparez-vous pour la reprise d'activité BlueXP

* Vérifiez votre environnement de production.
+
** Assurez-vous que les machines virtuelles que vous souhaitez protéger sont hébergées sur des datastores NFS (avec des volumes NFS ONTAP) ou des datastores VMFS (avec des LUN iSCSI NetApp).
** Assurez-vous que vous disposez des identifiants et des clés d'accès pour vos baies ONTAP sur site, vos vCenter et vos instances cloud VMware hébergées par AWS.


* Créez ou vérifiez votre site de reprise sur incident.
+
** Créez ou vérifiez que votre système de fichiers Amazon FSX est prêt.
** Vérifiez que vos VM source et de destination sont bien peering.






== Configurez le SDDC VMware Cloud pour AWS

Configuration du data Center Software-defined (SDDC) VMware Cloud for AWS

* Créez un système de fichiers Amazon FSX pour ONTAP. Provisionnez et configurez FSX pour ONTAP. Amazon FSX pour NetApp ONTAP est un service entièrement géré qui offre un stockage de fichiers extrêmement fiable, évolutif, haute performance et riche en fonctionnalités basé sur le système de fichiers populaire NetApp ONTAP.
* Suivez les étapes ci https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["lien"^] -dessous et ici https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Démarrage rapide d'Amazon FSX pour NetApp ONTAP"] pour provisionner et configurer FSX pour NetApp ONTAP.
* Ajoutez Amazon FSX pour NetApp ONTAP à l'environnement de travail et les identifiants AWS pour FSX pour ONTAP.
* Dans AWS, vous devez effectuer les étapes suivantes :
+
** Déploiement et configuration de VMware Cloud sur AWS
** Utiliser un compte VMware et provisionner le SDDC. Assurez-vous que le SDDC est connecté à FSX for ONTAP.






=== Déploiement de VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud sur AWS"^] Offre une expérience cloud native pour les charges de travail VMware dans l'écosystème AWS. Chaque data Center Software-defined VMware (SDDC) s'exécute dans un cloud privé virtuel Amazon et fournit une pile VMware complète (y compris vCenter Server), une mise en réseau Software-defined NSX-T, un stockage Software-defined VSAN et un ou plusieurs hôtes ESXi qui fournissent des ressources de calcul et de stockage aux charges de travail.

Pour configurer un environnement VMC sur AWS, procédez comme suit https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["lien"^]. Un bloc de voyants peut également être utilisé à des fins de reprise après incident.
