---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas 
summary: 'BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. Avec la reprise d"activité BlueXP pour VMware, vous pouvez répliquer vos workloads VMware sur site exécutant un stockage ONTAP vers un data Center Software-defined VMware dans des clouds publics comme site de reprise d"activité à l"aide du stockage cloud NetApp.' 
---
= Nouveautés de la reprise d'activité BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés de la reprise d'activité BlueXP.



== 30 octobre 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Reporting*: Avec cette version, vous pouvez maintenant générer et télécharger des rapports pour vous aider à analyser votre paysage. Des rapports prédéfinis résument les basculements et les basculements, affichent les détails de réplication sur tous les sites et affichent les détails des tâches des sept derniers jours.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Créez des rapports de reprise d'activité"].

* *Essai gratuit de 30 jours* : avec cette version, vous pouvez maintenant vous inscrire pour un essai gratuit de 30 jours de la reprise après sinistre BlueXP . Auparavant, les essais gratuits étaient de 90 jours.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configuration des licences"].

* *Désactiver et activer les plans de réplication* : une version précédente comprenait des mises à jour de la structure de planification des tests de basculement, qui était nécessaire pour prendre en charge les plannings quotidiens et hebdomadaires. Cette mise à jour exige que vous désactiviez et réactiviez tous les plans de réplication existants afin de pouvoir utiliser les nouveaux programmes de tests de basculement quotidiens et hebdomadaires. Il s'agit d'une exigence ponctuelle.
+
Voici comment :

+
.. Dans le menu supérieur, sélectionnez *plans de réplication*.
.. Sélectionnez un plan et sélectionnez l'icône actions pour afficher le menu déroulant.
.. Sélectionnez *Désactiver*.
.. Après quelques minutes, sélectionnez *Activer*.


* *Mappage de dossiers* : lorsque vous créez un plan de réplication et mappez des ressources de calcul, vous pouvez maintenant mapper des dossiers de sorte que les machines virtuelles soient restaurées dans un dossier que vous spécifiez pour le centre de données, le cluster et l'hôte.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Informations sur les machines virtuelles disponibles pour le basculement, le retour arrière et le basculement de test* : lorsqu'une panne se produit et que vous démarrez un basculement, effectuez un retour arrière ou testez le basculement, vous pouvez désormais afficher les détails des machines virtuelles et identifier celles qui n'ont pas redémarré.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].

* *Délai de démarrage de la machine virtuelle avec séquence de démarrage ordonnée* : lorsque vous créez un plan de réplication, vous pouvez maintenant définir un délai de démarrage pour chaque machine virtuelle du plan. Cela vous permet de définir une séquence pour que les machines virtuelles commencent à s'assurer que toutes vos machines virtuelles prioritaires sont en cours d'exécution avant que les machines virtuelles prioritaires suivantes ne soient démarrées.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Informations sur le système d'exploitation VM* : lorsque vous créez un plan de réplication, vous pouvez maintenant voir le système d'exploitation de chaque VM dans le plan. Ceci est utile pour décider comment regrouper des machines virtuelles dans un groupe de ressources.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Alias de nom de VM* : lorsque vous créez un plan de réplication, vous pouvez maintenant ajouter un préfixe et un suffixe aux noms de VM sur le SIT de reprise après sinistre. Cela vous permet d'utiliser un nom plus descriptif pour les VM du plan.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Nettoyer les anciens snapshots* : avec cette version, vous pouvez supprimer tous les snapshots qui ne sont plus nécessaires au-delà du nombre de rétention spécifié. Les snapshots peuvent s'accumuler au fil du temps lorsque vous réduisez le nombre de conservation des snapshots et vous pouvez désormais les supprimer pour libérer de l'espace. Vous pouvez le faire à tout moment à la demande ou lorsque vous supprimez un plan de réplication.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérez les sites, les groupes de ressources, les plans de réplication, les datastores et les informations sur les machines virtuelles"] .

* *Réconcilier instantanés* : avec cette version, vous pouvez désormais réconcilier les instantanés qui sont désynchronisés entre la source et la cible. Cela peut se produire si des snapshots sont supprimés sur une cible en dehors de la reprise sur incident BlueXP . Le service supprime automatiquement le snapshot sur la source toutes les 24 heures. Cependant, vous pouvez effectuer cette opération à la demande. Cette fonction vous permet de vous assurer que les snapshots sont cohérents sur tous les sites.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans de réplication"] .





== 20 septembre 2024

Cette version de reprise sur incident BlueXP  inclut la mise à jour suivante.

* *Prise en charge des datastores VMware VMFS sur site à sur site* : cette version inclut la prise en charge des machines virtuelles montées sur des datastores VMware vSphere Virtual machine File System (VMFS) pour iSCSI et FC protégées sur le stockage sur site. Auparavant, le service fournissait un _aperçu de la technologie_ prenant en charge les datastores VMFS pour iSCSI et FC.
+
Voici quelques considérations supplémentaires concernant à la fois les protocoles iSCSI et FC :

+
** La prise en charge de FC concerne les protocoles client frontaux, pas la réplication.
** La reprise d'activité BlueXP  ne prend en charge qu'une seule LUN par volume ONTAP. Le volume ne doit pas avoir plusieurs LUN.
** Pour tout plan de réplication, le volume ONTAP de destination doit utiliser les mêmes protocoles que le volume ONTAP source hébergeant les VM protégées. Par exemple, si la source utilise un protocole FC, la destination doit également utiliser FC.






== 2 août 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Prise en charge des datastores VMware VMFS sur site à sur site pour FC* : cette version inclut un _aperçu technologique_ de la prise en charge des machines virtuelles montées sur des datastores VMware vSphere Virtual machine File System (VMFS) pour FC protégés sur stockage sur site. Auparavant, le service offrait un aperçu de la technologie prenant en charge les datastores VMFS pour iSCSI.
+

NOTE: NetApp ne vous facture pas pour la capacité de workloads prévisualisée.

* *Job CANCEL* : avec cette version, vous pouvez maintenant annuler un travail dans l'interface utilisateur de Job Monitor.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Surveiller les tâches"].





== 17 juillet 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Plannings de test de basculement* : cette version inclut des mises à jour de la structure de planification de test de basculement, qui était nécessaire pour prendre en charge les plannings quotidiens et hebdomadaires. Cette mise à jour nécessite que vous désactiviez et réactiviez tous les plans de réplication existants afin de pouvoir utiliser les nouveaux programmes de tests de basculement quotidiens et hebdomadaires. Il s'agit d'une exigence ponctuelle.
+
Voici comment :

+
.. Dans le menu supérieur, sélectionnez *plans de réplication*.
.. Sélectionnez un plan et sélectionnez l'icône actions pour afficher le menu déroulant.
.. Sélectionnez *Désactiver*.
.. Après quelques minutes, sélectionnez *Activer*.


* *Mises à jour du plan de réplication* : cette version inclut des mises à jour des données du plan de réplication, ce qui résout un problème de "snapshot introuvable". Pour ce faire, vous devez définir le nombre de rétention dans tous les plans de réplication sur 1 et lancer un instantané à la demande. Ce processus crée une nouvelle sauvegarde et supprime toutes les anciennes sauvegardes.
+
Voici comment :

+
.. Dans le menu supérieur, sélectionnez *plans de réplication*.
.. Sélectionnez le plan de réplication, cliquez sur l'onglet *mappage de basculement*, puis cliquez sur l'icône crayon *Modifier*.
.. Cliquez sur la flèche *datastores* pour la développer.
.. Notez la valeur du nombre de rétention dans le plan de réplication. Vous devrez rétablir cette valeur d'origine lorsque vous aurez terminé ces étapes.
.. Réduisez le compte à 1.
.. Lancez un snapshot à la demande. Pour ce faire, sur la page Plan de réplication, sélectionnez le plan, cliquez sur l'icône actions et sélectionnez *prendre instantané maintenant*.
.. Une fois la procédure de snapshot terminée, augmentez le nombre dans le plan de réplication à sa valeur d'origine, que vous avez notée à la première étape.
.. Répétez ces étapes pour tous les plans de réplication existants.






== 5 juillet 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Prise en charge de AFF série A* : cette version prend en charge les plates-formes matérielles NetApp AFF série A.


* *Prise en charge des datastores VMware VMFS sur site à sur site* : cette version inclut un _aperçu technologique_ de la prise en charge des machines virtuelles montées sur des datastores VMFS (Virtual machine File System) VMware vSphere protégés sur le stockage sur site. Avec cette version, la reprise après incident est prise en charge dans un aperçu technologique pour les workloads VMware sur site vers un environnement VMware sur site avec des datastores VMFS.
+

NOTE: NetApp ne vous facture pas pour la capacité de workloads prévisualisée.

* *Mises à jour du plan de réplication* : vous pouvez ajouter un plan de réplication plus facilement en filtrant les machines virtuelles par datastore sur la page applications et en selecti//reportez-vous à link:../use/drplan-create.html["Créer un plan de réplication"]. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"]. Ng plus de détails sur les cibles sur la page mappage des ressources.
* *Modifier les plans de réplication* : avec cette version, la page mappages de basculement a été améliorée pour plus de clarté.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans"].

* *Edit VM* : avec cette version, le processus de modification des machines virtuelles dans le plan comprenait quelques améliorations mineures de l'interface utilisateur.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestion des VM"].

* *Basculement des mises à jour* : avant de lancer un basculement, vous pouvez maintenant déterminer l'état des machines virtuelles et s'ils sont sous ou hors tension. Le processus de basculement vous permet maintenant de prendre un instantané ou de choisir les snapshots.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].

* *Plannings de test de basculement* : vous pouvez maintenant modifier les tests de basculement et définir des plannings quotidiens, hebdomadaires et mensuels pour le test de basculement.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans"].

* *Mises à jour des informations prérequis* : les informations sur les conditions préalables à la reprise d'activité BlueXP ont été mises à jour.
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Conditions préalables à la reprise d'activité BlueXP"].





== 15 mai 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *La réplication des charges de travail VMware du stockage sur site vers le stockage sur site* est maintenant proposée en tant que fonction de disponibilité générale. Auparavant, il s'agissait d'un aperçu technologique avec des fonctionnalités limitées.
* *Mises à jour des licences* : avec BlueXP Disaster Recovery, vous pouvez vous inscrire à un essai gratuit de 90 jours, acheter un abonnement PAYGO avec Amazon Marketplace ou BYOL (Bring Your Own License), un fichier de licence NetApp (NLF) que vous pouvez obtenir auprès de votre ingénieur commercial NetApp ou auprès du site de support NetApp (NSS).
+
Pour plus d'informations sur la configuration des licences pour la reprise d'activité BlueXP, reportez-vous à la section link:../get-started/dr-licensing.html["Configuration des licences"].



https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].



== 5 mars 2024

Il s'agit de la version General Availability de BlueXP Disaster Recovery, qui comprend les mises à jour suivantes.

* *Mises à jour des licences* : avec BlueXP Disaster Recovery, vous pouvez vous inscrire à un essai gratuit de 90 jours ou demander votre propre licence (BYOL), qui est un fichier de licence NetApp (NLF) que vous obtenez auprès de votre ingénieur commercial NetApp Vous pouvez utiliser le numéro de série de licence pour activer la fonction BYOL dans le portefeuille digital BlueXP. Les frais de reprise d'activité BlueXP sont calculés en fonction de la capacité provisionnée des datastores.
+
Pour plus d'informations sur la configuration des licences pour la reprise d'activité BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configuration des licences"].

+
Pour plus d'informations sur la gestion des licences pour *tous* services BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Gérez les licences de tous les services BlueXP"^].



* *Modifier les plannings*: Avec cette version, vous pouvez maintenant configurer des calendriers pour tester les tests de conformité et de basculement afin de vous assurer qu'ils fonctionneront correctement si vous en avez besoin.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créez le plan de réplication"].





== 1er février 2024

Cette version de préversion de la reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Amélioration du réseau* : avec cette version, vous pouvez désormais redimensionner les valeurs CPU et RAM de la machine virtuelle. Vous pouvez également sélectionner une adresse IP statique ou DHCP réseau pour la machine virtuelle.
+
** DHCP : si vous choisissez cette option, vous fournissez les informations d'identification de la machine virtuelle.
** IP statique : vous pouvez sélectionner les mêmes informations ou des informations différentes à partir de la machine virtuelle source. Si vous choisissez la même chose que la source, vous n'avez pas besoin d'entrer les informations d'identification. En revanche, si vous choisissez d'utiliser des informations différentes de la source, vous pouvez fournir les informations d'identification, l'adresse IP, le masque de sous-réseau, le DNS et la passerelle.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



* *Les scripts personnalisés* peuvent maintenant être inclus comme processus de post-basculement. Avec les scripts personnalisés, la reprise d'activité BlueXP peut exécuter votre script après un processus de basculement. Par exemple, vous pouvez utiliser un script personnalisé pour reprendre toutes les transactions de base de données une fois le basculement terminé.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculez vers un site distant"].

* *Relation SnapMirror* : vous pouvez maintenant créer une relation SnapMirror tout en développant le plan de réplication. Auparavant, vous deviez créer la relation en dehors de la reprise d'activité BlueXP.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Groupes de cohérence* : lorsque vous créez un plan de réplication, vous pouvez inclure des machines virtuelles provenant de différents volumes et de différents SVM. La reprise d'activité BlueXP crée une copie Snapshot de groupe de cohérence en incluant tous les volumes et en mettant à jour tous les sites secondaires.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Option de délai de mise sous tension de la machine virtuelle* : lorsque vous créez un plan de réplication, vous pouvez ajouter des machines virtuelles à un groupe de ressources. Avec Resource Groups, vous pouvez définir un délai sur chaque machine virtuelle afin qu'elle se met sous tension en séquence différée.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Copies Snapshot cohérentes au niveau des applications* : vous pouvez spécifier de créer des copies Snapshot cohérentes au niveau des applications. Le service arrête l'application, puis prend un Snapshot pour obtenir un état cohérent de l'application.
+
Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].





== 11 janvier 2024

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes :

* Cette version vous permet d'accéder plus rapidement aux informations d'autres pages du tableau de bord.


https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Découvrez la reprise d'activité BlueXP"].



== 20 octobre 2023

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes.

Désormais, avec la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS contre les incidents vers un autre environnement VMware sur site et NFS en plus du cloud public. La reprise d'activité BlueXP orchestre l'achèvement des plans de reprise d'activité.


NOTE: Avec cette offre de prévisualisation, NetApp se réserve le droit de modifier les détails, le contenu et le calendrier de l'offre avant la disponibilité générale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].



== 27 septembre 2023

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes :

* *Mises à jour du tableau de bord* : vous pouvez maintenant cliquer sur les options du tableau de bord, ce qui vous permet de passer rapidement en revue l'information. De plus, le tableau de bord affiche désormais l'état des basculements et des migrations.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Consultez l'état de vos plans de reprise sur incident dans le tableau de bord"].

* *Mises à jour du plan de réplication* :
+
** *RPO* : vous pouvez maintenant saisir l'objectif de point de récupération (RPO) et le nombre de rétention dans la section datastores du plan de réplication. Indique la quantité de données qui doit exister et qui n'est pas antérieure à l'heure définie. Si, par exemple, vous le configurez à 5 minutes, le système peut perdre jusqu'à 5 minutes de données en cas d'incident sans affecter les besoins stratégiques de l'entreprise.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

** *Améliorations de la mise en réseau* : lorsque vous mappez la mise en réseau entre les emplacements source et cible dans la section machines virtuelles du plan de réplication, BlueXP Disaster Recovery propose désormais deux options : DHCP ou IP statique. Auparavant, seul DHCP était pris en charge. Pour les adresses IP statiques, vous configurez le sous-réseau, la passerelle et les serveurs DNS. En outre, vous pouvez maintenant saisir des informations d'identification pour les machines virtuelles.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

** *Modifier les plannings* : vous pouvez maintenant mettre à jour les plannings de plans de réplication.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les ressources"].

** *SnapMirror automation* : lors de la création du plan de réplication dans cette version, vous pouvez définir la relation SnapMirror entre les volumes source et cible dans l'une des configurations suivantes :
+
*** 1 à 1
*** 1 à plusieurs dans une architecture en éventail
*** De plusieurs à 1 en tant que groupe de cohérence
*** De plusieurs à plusieurs
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].









== 1er août 2023

La préversion de la reprise d'activité BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. À l'aide de la préversion de la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS exécutant le stockage NetApp vers VMware Cloud (VMC) sur AWS avec Amazon FSX pour ONTAP.


NOTE: Avec cette offre de prévisualisation, NetApp se réserve le droit de modifier les détails, le contenu et le calendrier de l'offre avant la disponibilité générale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].

Cette version comprend les mises à jour suivantes :

* *Mise à jour des groupes de ressources pour l'ordre d'amorçage* : lorsque vous créez un plan de reprise après sinistre ou de réplication, vous pouvez ajouter des machines virtuelles à des groupes de ressources fonctionnelles. Les groupes de ressources vous permettent de placer un ensemble de machines virtuelles dépendantes dans des groupes logiques qui répondent à vos besoins. Par exemple, les groupes peuvent contenir un ordre de démarrage qui peut être exécuté lors de la restauration. Avec cette version, chaque groupe de ressources peut inclure une ou plusieurs machines virtuelles. Les machines virtuelles s'allume en fonction de l'ordre dans lequel vous les incluez dans le plan. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Sélectionnez les applications à répliquer et attribuez des groupes de ressources"].
* *Vérification de la réplication* : après avoir créé le plan de reprise après incident ou de réplication, identifiez la récurrence dans l'assistant et lancez une réplication vers un site de reprise après incident, toutes les 30 minutes, BlueXP Disaster Recovery vérifie que la réplication se produit réellement conformément au plan. Vous pouvez surveiller la progression dans la page moniteur des tâches. Reportez-vous à la section  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Réplication d'applications vers un autre site"].
* *Le plan de réplication affiche les programmes de transfert de l'objectif de point de récupération (RPO)* : lorsque vous créez un plan de reprise après sinistre ou de réplication, vous sélectionnez les machines virtuelles. Dans cette version, vous pouvez désormais afficher la SnapMirror associée à chacun des volumes associés au datastore ou à la machine virtuelle. Vous pouvez également consulter les planifications de transfert RPO associées à la planification SnapMirror. L'objectif de point de récupération vous permet de déterminer si votre planification de sauvegarde est suffisante pour permettre une reprise après incident. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].
* *Mise à jour du moniteur de tâches* : la page moniteur de tâches comprend maintenant une option d'actualisation qui vous permet d'obtenir un état à jour des opérations. Reportez-vous à la section  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Surveiller les tâches de reprise après incident"].




== 18 mai 2023

Il s'agit de la version initiale de la reprise d'activité de BlueXP.

BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. À l'aide de la préversion de la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS exécutant le stockage NetApp vers VMware Cloud (VMC) sur AWS avec Amazon FSX pour ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].
