---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: 'BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. Avec la reprise d"activité BlueXP pour VMware, vous pouvez répliquer vos workloads VMware sur site exécutant un stockage ONTAP vers un data Center Software-defined VMware dans des clouds publics comme site de reprise d"activité à l"aide du stockage cloud NetApp.' 
---
= Nouveautés de la reprise d'activité BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés de la reprise d'activité BlueXP.



== 15 septembre 2025

Version 4.3.5P3



=== Configuration du script pour le test de basculement

Avec cette version, vous pouvez désormais exécuter des scripts sur les machines virtuelles après leur mise sous tension pendant le processus de basculement de test.  Cela vous permet de tester et de valider des scripts.  Par exemple, vous pouvez mettre à jour les montages NFS pour pointer vers un nouveau serveur cible, garantissant ainsi que les applications invitées sont entièrement en ligne et que votre processus de récupération peut être testé de bout en bout.

Pour plus d'informations sur le processus de basculement, voirlink:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"] .



=== Processus de restauration automatique amélioré

Lors du basculement, le processus de restauration automatique est désormais désactivé jusqu'à ce que la découverte soit terminée.  Cela garantit que toutes les configurations sont correctement identifiées et prises en compte avant de lancer une restauration, et réduit le risque d'erreurs.

Pour plus d'informations sur le processus de restauration automatique, voirlink:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failback.html["Rétablir la source d'origine des applications"] .



== 04 août 2025

Version 4.2.5P2



=== Mises à jour de BlueXP disaster recovery

Cette version comprend les mises à jour suivantes :

* Amélioration de la prise en charge VMFS pour gérer le même LUN présenté à partir de plusieurs machines virtuelles de stockage.
* Amélioration du nettoyage du démontage des tests pour gérer le magasin de données déjà démonté et/ou supprimé.
* Mappage de sous-réseau amélioré afin qu'il valide désormais que la passerelle saisie est contenue dans le réseau fourni.
* Correction d'un problème qui pouvait entraîner l'échec du plan de réplication si le nom de la machine virtuelle contenait « .com ».
* Suppression d'une restriction empêchant le volume de destination d'être identique au volume source lors de la création du volume dans le cadre de la création du plan de réplication.
* Ajout de la prise en charge d’un abonnement à la carte (PAYGO) aux services intelligents NetApp dans Azure Marketplace et ajout d’un lien vers Azure Marketplace dans la boîte de dialogue d’essai gratuit.
+
Pour plus de détails, voir https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["Licence de BlueXP disaster recovery"] et https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurez les licences pour la reprise d'activité BlueXP"] .





== 14 juillet 2025

Version 4.2.5



=== Rôles des utilisateurs dans la BlueXP disaster recovery

La BlueXP disaster recovery utilise désormais des rôles pour gérer l’accès de chaque utilisateur à des fonctionnalités et actions spécifiques.

Le service utilise les rôles suivants qui sont spécifiques à la BlueXP disaster recovery.

* *Administrateur de récupération après sinistre* : effectuez toutes les actions dans la BlueXP disaster recovery.
* *Administrateur de basculement de reprise après sinistre* : effectuez des actions de basculement et de migration dans la BlueXP disaster recovery.
* *Administrateur d'application de récupération après sinistre* : Créez et modifiez des plans de réplication et démarrez des tests de basculement.
* *Visionneuse de récupération après sinistre* : affichez les informations dans la BlueXP disaster recovery, mais ne pouvez effectuer aucune action.


Si vous cliquez sur le service de BlueXP disaster recovery et le configurez pour la première fois, vous devez disposer de l'autorisation *SnapCenterAdmin* ou du rôle *Administrateur d'organisation*.

Pour plus de détails, voir  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Rôles et autorisations des utilisateurs dans la BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].



=== Autres mises à jour de la BlueXP disaster recovery

* Découverte de réseau améliorée
* Améliorations de l'évolutivité :
+
** Filtrage des métadonnées requises au lieu de tous les détails
** Améliorations de la découverte pour récupérer et mettre à jour les ressources des machines virtuelles plus rapidement
** Optimisation de la mémoire et des performances pour la récupération et la mise à jour des données
** Améliorations de la création de clients vCenter SDK et de la gestion des pools


* Gestion des données obsolètes lors de la prochaine découverte planifiée ou manuelle :
+
** Lorsqu'une machine virtuelle est supprimée dans vCenter, la BlueXP disaster recovery la supprime désormais automatiquement du plan de réplication.
** Lorsqu'une banque de données ou un réseau est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.
** Lorsqu'un cluster, un hôte ou un centre de données est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.


* Vous pouvez désormais accéder à la documentation Swagger en mode navigation privée. Vous pouvez y accéder depuis la BlueXP disaster recovery via Paramètres > Documentation API ou directement à l'URL suivante en mode navigation privée :  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentation Swagger"^] .
* Dans certains cas, après une restauration automatique, l'iGroup était conservé une fois l'opération terminée. Cette mise à jour supprime l'iGroup s'il est obsolète.
* Si le nom de domaine complet NFS était utilisé dans le plan de réplication, la BlueXP disaster recovery le résout désormais en adresse IP. Cette mise à jour est utile si le nom de domaine complet n'est pas résoluble sur le site de reprise après sinistre.
* Améliorations de l'alignement de l'interface utilisateur
* Améliorations du journal pour capturer les détails de dimensionnement de vCenter après la découverte réussie




== 30 juin 2025

Version 4.2.4P2



=== Améliorations de la découverte

Cette mise à jour améliore le processus de découverte, ce qui réduit le temps nécessaire à la découverte.



== 23 juin 2025

Version 4.2.4P1



=== Améliorations du mappage des sous-réseaux

Cette mise à jour améliore la boîte de dialogue « Ajouter et modifier le mappage de sous-réseaux » avec une nouvelle fonctionnalité de recherche. Vous pouvez désormais trouver rapidement des sous-réseaux spécifiques en saisissant des termes de recherche, ce qui simplifie la gestion des mappages de sous-réseaux.



== 9 juin 2025

Version 4.2.4



=== Prise en charge de la solution de mot de passe d'administrateur local Windows (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) est une fonctionnalité Windows qui gère et sauvegarde automatiquement le mot de passe d'un compte administrateur local sur Active Directory.

Vous pouvez désormais sélectionner les options de mappage de sous-réseau et cocher l'option LAPS en fournissant les informations du contrôleur de domaine. Grâce à cette option, vous n'avez pas besoin de fournir de mot de passe pour chacune de vos machines virtuelles.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



== 13 mai 2025

Version 4.2.3



=== Mappage de sous-réseau

Avec cette version, vous pouvez gérer les adresses IP en cas de basculement de manière nouvelle à l'aide du mappage de sous-réseau, qui vous permet d'ajouter des sous-réseaux pour chaque vCenter. Dans ce cas, vous définissez le CIDR IPv4, la passerelle par défaut et le DNS pour chaque réseau virtuel.

Lors du basculement, la reprise après incident BlueXP  détermine l'adresse IP appropriée de chaque vNIC en examinant le CIDR fourni pour le réseau virtuel mappé et l'utilise pour dériver la nouvelle adresse IP.

Par exemple :

* Réseau a = 10.1.1.0/24
* Réseau B = 192.168.1.0/24


VM1 dispose d'une vNIC (10.1.1.50) connectée au réseau A. NetworkA est mappé sur le réseau B dans les paramètres du plan de réplication.

En cas de basculement, la reprise après incident BlueXP  remplace la partie réseau de l'adresse IP d'origine (10.1.1) et conserve l'adresse hôte (.50) de l'adresse IP d'origine (10.1.1.50). Pour VM1, BlueXP  Disaster Recovery examine les paramètres CIDR du réseau B et utilise cette partie du réseau 192.168.1 tout en conservant la partie hôte (.50) pour créer la nouvelle adresse IP du VM1. La nouvelle adresse IP devient 192.168.1.50.

En résumé, l'adresse de l'hôte reste la même, tandis que l'adresse réseau est remplacée par celle configurée dans le mappage de sous-réseau du site. Cela vous permet de gérer plus facilement la réaffectation d'adresses IP en cas de basculement, notamment si vous avez des centaines de réseaux et des milliers de machines virtuelles à gérer.

Pour plus d'informations sur l'inclusion du mappage de sous-réseau dans vos sites, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Ajoutez des sites de serveur vCenter"] .



=== Ignorer la protection

Vous pouvez maintenant ignorer la protection afin que le service ne crée pas automatiquement une relation de protection inverse après un basculement de plan de réplication. Cette fonction est utile si vous souhaitez effectuer des opérations supplémentaires sur le site restauré avant de le remettre en ligne dans le cadre de la reprise sur incident BlueXP .

Lorsque vous initiez un basculement, par défaut, le service crée automatiquement une relation de protection inverse pour chaque volume du plan de réplication, si le site source d'origine est en ligne. Cela signifie que le service crée une relation SnapMirror entre le site cible et le site source. Par ailleurs, le service inverse automatiquement la relation SnapMirror lorsque vous initiez un retour arrière.

Lorsque vous lancez un basculement, vous pouvez maintenant choisir une option *Ignorer la protection*. Avec cela, le service n'inverse pas automatiquement la relation SnapMirror. Il laisse le volume inscriptible des deux côtés du plan de réplication.

Une fois le site source d'origine remis en ligne, vous pouvez établir une protection inverse en sélectionnant *protéger les ressources* dans le menu actions du plan de réplication. Cette opération tente de créer une relation de réplication inverse pour chaque volume du plan. Vous pouvez exécuter cette tâche plusieurs fois jusqu'à ce que la protection soit restaurée. Une fois la protection restaurée, vous pouvez lancer un rétablissement de la manière habituelle.

Pour plus de détails sur le fait d'ignorer la protection, reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].



=== SnapMirror planifie les mises à jour dans le plan de réplication

La reprise sur incident BlueXP  prend désormais en charge l'utilisation de solutions de gestion externe des snapshots, comme le planificateur de règles ONTAP SnapMirror natif ou les intégrations tierces avec ONTAP. Si chaque datastore (volume) du plan de réplication dispose déjà d'une relation SnapMirror gérée par un autre emplacement, vous pouvez utiliser ces snapshots comme points de restauration dans la reprise d'activité BlueXP .

Pour configurer, dans la section Replication Plan > Resource Mapping, cochez la case *utiliser les sauvegardes gérées par la plate-forme et les plannings de rétention* lors de la configuration du mappage des datastores.

Lorsque cette option est sélectionnée, la reprise sur incident BlueXP  ne configure pas de programme de sauvegarde. Toutefois, vous devez toujours configurer un planning de conservation, car les snapshots peuvent toujours être créés pour les opérations de test, de basculement et de restauration.

Une fois configuré, le service ne prend pas de snapshots planifiés régulièrement, mais s'appuie plutôt sur l'entité externe pour prendre et mettre à jour ces snapshots.

Pour plus d'informations sur l'utilisation de solutions d'instantanés externes dans le plan de réplication, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



== 16 avril 2025

Version 4.2.2



=== Découverte planifiée pour les VM

La reprise sur incident BlueXP  effectue une détection toutes les 24 heures. Avec cette version, vous pouvez désormais personnaliser le calendrier de découverte pour répondre à vos besoins et réduire l'impact sur les performances lorsque vous en avez besoin. Par exemple, si vous disposez d'un grand nombre de machines virtuelles, vous pouvez définir la planification de la découverte pour qu'elle s'exécute toutes les 48 heures. Si vous disposez d'un petit nombre de machines virtuelles, vous pouvez définir la planification de découverte pour qu'elle s'exécute toutes les 12 heures.

Si vous ne souhaitez pas que wan planifie la découverte, vous pouvez désactiver l'option de découverte planifiée et actualiser la découverte manuellement à tout moment.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Ajoutez des sites de serveur vCenter"] .



=== Prise en charge des datastores de groupes de ressources

Auparavant, vous ne pouviez créer des groupes de ressources que par des machines virtuelles. Avec cette version, vous pouvez créer un groupe de ressources par datastores. Lorsque vous créez un plan de réplication et un groupe de ressources pour ce plan, toutes les machines virtuelles d'un datastore sont répertoriées. Cette option est utile si vous disposez d'un grand nombre de machines virtuelles et que vous souhaitez les regrouper par datastore.

Vous pouvez créer un groupe de ressources avec un datastore de l'une des manières suivantes :

* Lorsque vous ajoutez un groupe de ressources à l'aide de datastores, vous pouvez voir la liste des datastores. Vous pouvez sélectionner un ou plusieurs datastores pour créer un groupe de ressources.
* Lorsque vous créez un plan de réplication et un groupe de ressources dans le plan, vous pouvez voir les machines virtuelles dans les datastores.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Notifications d'expiration de licence ou d'essai gratuit

Cette version fournit des notifications indiquant que l'essai gratuit expirera dans 60 jours pour vous assurer que vous avez le temps d'obtenir une licence. Cette version fournit également des notifications le jour de l'expiration de la licence.



=== Notification des mises à jour de service

Avec cette version, une bannière s'affiche en haut pour indiquer que les services sont en cours de mise à niveau et que le service est placé en mode de maintenance. La bannière s'affiche lorsque le service est mis à niveau et disparaît lorsque la mise à niveau est terminée. Bien que vous puissiez continuer à travailler dans l'interface utilisateur pendant la mise à niveau, vous ne pouvez pas soumettre de nouveaux travaux. Les tâches planifiées s'exécuteront une fois la mise à jour terminée et le service retournera en mode de production.



== 10 mars 2025

Version 4.2.1



=== Prise en charge de proxy intelligent

Le connecteur BlueXP  prend en charge le proxy intelligent. Le proxy intelligent est un moyen léger, sécurisé et efficace de connecter votre environnement sur site au service BlueXP . Il fournit une connexion sécurisée entre votre environnement et le service BlueXP  sans VPN ni accès direct à Internet. Cette mise en œuvre de proxy optimisée décharge le trafic API au sein du réseau local.

Lorsqu'un proxy est configuré, la reprise après incident BlueXP  tente de communiquer directement avec VMware ou ONTAP et utilise le proxy configuré en cas d'échec de la communication directe.

La mise en œuvre du proxy de reprise après incident BlueXP  nécessite une communication sur le port 443 entre le connecteur et tous les serveurs vCenter et baies ONTAP utilisant un protocole HTTPS. L'agent de reprise après incident BlueXP  intégré au connecteur communique directement avec VMware vSphere, VC ou ONTAP lors de l'exécution de toute action.

Pour plus d'informations sur le proxy intelligent pour la reprise après incident BlueXP , reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Configurez votre infrastructure pour la reprise d'activité BlueXP"].

Pour plus d'informations sur la configuration générale du proxy dans BlueXP , reportez-vous à la section https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configurez un connecteur pour utiliser un serveur proxy"^].



=== Terminez l'essai gratuit à tout moment

Vous pouvez arrêter l'essai gratuit à n'importe quelle dent ou vous pouvez attendre jusqu'à ce qu'il expire.

Voir https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Terminez l'essai gratuit"].



== 19 février 2025

Version 4.2



=== Prise en charge de ASA r2 pour les machines virtuelles et les datastores sur stockage VMFS

Cette version de BlueXP  Disaster Recovery prend en charge ASA r2 pour les machines virtuelles et les datastores sur le stockage VMFS. Sur un système ASA r2, le logiciel ONTAP prend en charge les fonctionnalités SAN essentielles, tout en supprimant les fonctionnalités non prises en charge dans les environnements SAN.

Cette version prend en charge les fonctionnalités suivantes pour ASA r2 :

* Provisionnement de groupes de cohérence pour le stockage primaire (groupe de cohérence plat uniquement, c'est-à-dire un seul niveau sans structure hiérarchique)
* Opérations de sauvegarde (groupe de cohérence) incluant l'automatisation SnapMirror


La prise en charge de ASA r2 dans la reprise sur incident BlueXP  utilise ONTAP 9.16.1.

Les datastores peuvent être montés sur un volume ONTAP ou une unité de stockage ASA r2, mais un groupe de ressources dans BlueXP  Disaster Recovery ne peut pas inclure à la fois un datastore depuis ONTAP et un datastore depuis ASA r2. Vous pouvez sélectionner un datastore à partir de ONTAP ou un datastore à partir de ASA r2 dans un groupe de ressources.



== 30 octobre 2024



=== Création de rapports

Vous pouvez désormais générer et télécharger des rapports pour vous aider à analyser votre environnement. Des rapports prédéfinis résument les basculements et les basculements, affichent les détails de réplication sur tous les sites et affichent les détails des tâches des sept derniers jours.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Créez des rapports de reprise d'activité"].



=== essai gratuit de 30 jours

Vous pouvez désormais vous inscrire pour bénéficier d'un essai gratuit de 30 jours de reprise d'activité BlueXP . Auparavant, les essais gratuits étaient de 90 jours.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configuration des licences"].



=== Désactivez et activez les plans de réplication

Une version précédente incluait des mises à jour de la structure de planification des tests de basculement, qui devait prendre en charge les planifications quotidiennes et hebdomadaires. Cette mise à jour exige que vous désactiviez et réactiviez tous les plans de réplication existants afin de pouvoir utiliser les nouveaux programmes de tests de basculement quotidiens et hebdomadaires. Il s'agit d'une exigence ponctuelle.

Voici comment :

. Dans le menu supérieur, sélectionnez *plans de réplication*.
. Sélectionnez un plan et sélectionnez l'icône actions pour afficher le menu déroulant.
. Sélectionnez *Désactiver*.
. Après quelques minutes, sélectionnez *Activer*.




=== Mappage de dossiers

Lorsque vous créez un plan de réplication et que vous mappez des ressources de calcul, vous pouvez désormais mapper des dossiers de sorte que les machines virtuelles soient restaurées dans un dossier que vous spécifiez pour le centre de données, le cluster et l'hôte.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Détails sur les machines virtuelles disponibles pour le basculement, la restauration et le basculement de test

Lorsqu'une panne se produit et que vous démarrez un basculement, effectuez un retour arrière ou testez le basculement, vous pouvez désormais afficher les détails des machines virtuelles et identifier celles qui n'ont pas redémarré.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].



=== Délai de démarrage de la machine virtuelle avec séquence de démarrage ordonnée

Lorsque vous créez un plan de réplication, vous pouvez maintenant définir un délai de démarrage pour chaque machine virtuelle du plan. Cela vous permet de définir une séquence pour que les machines virtuelles commencent à s'assurer que toutes vos machines virtuelles prioritaires sont en cours d'exécution avant que les machines virtuelles prioritaires suivantes ne soient démarrées.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Informations sur le système d'exploitation des machines virtuelles

Lorsque vous créez un plan de réplication, vous pouvez maintenant voir le système d'exploitation pour chaque machine virtuelle du plan. Ceci est utile pour décider comment regrouper des machines virtuelles dans un groupe de ressources.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Alias de nom de VM

Lorsque vous créez un plan de réplication, vous pouvez à présent ajouter un préfixe et un suffixe aux noms des machines virtuelles sur le SIT de reprise après incident. Cela vous permet d'utiliser un nom plus descriptif pour les VM du plan.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Nettoyez les anciens snapshots

Vous pouvez supprimer tous les snapshots qui ne sont plus nécessaires au-delà du nombre de conservation spécifié. Les snapshots peuvent s'accumuler au fil du temps lorsque vous réduisez le nombre de conservation des snapshots et vous pouvez désormais les supprimer pour libérer de l'espace. Vous pouvez le faire à tout moment à la demande ou lorsque vous supprimez un plan de réplication.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérez les sites, les groupes de ressources, les plans de réplication, les datastores et les informations sur les machines virtuelles"] .



=== Réconcilier les instantanés

Vous pouvez désormais réconcilier les instantanés qui sont désynchronisés entre la source et la cible. Cela peut se produire si des snapshots sont supprimés sur une cible en dehors de la reprise sur incident BlueXP . Le service supprime automatiquement le snapshot sur la source toutes les 24 heures. Cependant, vous pouvez effectuer cette opération à la demande. Cette fonction vous permet de vous assurer que les snapshots sont cohérents sur tous les sites.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans de réplication"] .



== 20 septembre 2024



=== Prise en charge des datastores VMware VMFS sur site et sur site

Cette version inclut la prise en charge des machines virtuelles montées sur des datastores VMFS (Virtual machine File System) VMware vSphere pour iSCSI et FC protégées sur le stockage sur site. Auparavant, le service fournissait un _aperçu de la technologie_ prenant en charge les datastores VMFS pour iSCSI et FC.

Voici quelques considérations supplémentaires concernant à la fois les protocoles iSCSI et FC :

* La prise en charge de FC concerne les protocoles client frontaux, pas la réplication.
* La reprise d'activité BlueXP  ne prend en charge qu'une seule LUN par volume ONTAP. Le volume ne doit pas avoir plusieurs LUN.
* Pour tout plan de réplication, le volume ONTAP de destination doit utiliser les mêmes protocoles que le volume ONTAP source hébergeant les VM protégées. Par exemple, si la source utilise un protocole FC, la destination doit également utiliser FC.




== 2 août 2024



=== Prise en charge des datastores VMware VMFS pour FC sur site vers sur site

Cette version inclut un _aperçu de la technologie_ de la prise en charge des machines virtuelles montées sur des datastores VMFS (Virtual machine File System) VMware vSphere pour la protection FC sur un stockage sur site. Auparavant, le service offrait un aperçu de la technologie prenant en charge les datastores VMFS pour iSCSI.


NOTE: NetApp ne vous facture pas pour la capacité de workloads prévisualisée.



=== Annulation du travail

Avec cette version, vous pouvez maintenant annuler un travail dans l'interface utilisateur de Job Monitor.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Surveiller les tâches"].



== 17 juillet 2024



=== Planifications de tests de basculement

Cette version inclut des mises à jour de la structure de planification des tests de basculement, qui était nécessaire pour prendre en charge les planifications quotidiennes et hebdomadaires. Cette mise à jour nécessite que vous désactiviez et réactiviez tous les plans de réplication existants afin de pouvoir utiliser les nouveaux programmes de tests de basculement quotidiens et hebdomadaires. Il s'agit d'une exigence ponctuelle.

Voici comment :

. Dans le menu supérieur, sélectionnez *plans de réplication*.
. Sélectionnez un plan et sélectionnez l'icône actions pour afficher le menu déroulant.
. Sélectionnez *Désactiver*.
. Après quelques minutes, sélectionnez *Activer*.




=== Mises à jour du plan de réplication

Cette version inclut des mises à jour des données du plan de réplication, ce qui résout un problème de « snapshot introuvable ». Pour ce faire, vous devez définir le nombre de rétention dans tous les plans de réplication sur 1 et lancer un instantané à la demande. Ce processus crée une nouvelle sauvegarde et supprime toutes les anciennes sauvegardes.

Voici comment :

. Dans le menu supérieur, sélectionnez *plans de réplication*.
. Sélectionnez le plan de réplication, cliquez sur l'onglet *mappage de basculement*, puis cliquez sur l'icône crayon *Modifier*.
. Cliquez sur la flèche *datastores* pour la développer.
. Notez la valeur du nombre de rétention dans le plan de réplication. Vous devrez rétablir cette valeur d'origine lorsque vous aurez terminé ces étapes.
. Réduisez le compte à 1.
. Lancez un snapshot à la demande. Pour ce faire, sur la page Plan de réplication, sélectionnez le plan, cliquez sur l'icône actions et sélectionnez *prendre instantané maintenant*.
. Une fois la procédure de snapshot terminée, augmentez le nombre dans le plan de réplication à sa valeur d'origine, que vous avez notée à la première étape.
. Répétez ces étapes pour tous les plans de réplication existants.




== 5 juillet 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :



=== Prise en charge de AFF A-Series

Cette version prend en charge les plateformes matérielles NetApp AFF A-Series.



=== Prise en charge des datastores VMware VMFS sur site et sur site

Cette version inclut un _aperçu technologique_ de la prise en charge des machines virtuelles montées sur des datastores VMFS (Virtual machine File System) VMware vSphere protégés sur le stockage sur site. Avec cette version, la reprise après incident est prise en charge dans un aperçu technologique pour les workloads VMware sur site vers un environnement VMware sur site avec des datastores VMFS.


NOTE: NetApp ne vous facture pas pour la capacité de workloads prévisualisée.



=== Mises à jour du plan de réplication

Vous pouvez ajouter un plan de réplication plus facilement en filtrant les machines virtuelles par datastore sur la page applications et en sélectionnant plus de détails sur les cibles sur la page mappage des ressources. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Modifier les plans de réplication

Avec cette version, la page mappages de basculement a été améliorée pour plus de clarté.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans"].



=== Modifier les VM

Avec cette version, le processus de modification des machines virtuelles dans le plan comprenait quelques améliorations mineures de l'interface utilisateur.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestion des VM"].



=== Basculement des mises à jour

Avant d'initier un basculement, vous pouvez maintenant déterminer l'état des machines virtuelles et leur mise sous tension ou hors tension. Le processus de basculement vous permet maintenant de prendre un instantané ou de choisir les snapshots.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].



=== Planifications de tests de basculement

Vous pouvez désormais modifier les tests de basculement et définir des plannings quotidiens, hebdomadaires et mensuels pour le test de basculement.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans"].



=== Mise à jour des informations de prérequis

Les informations sur les conditions préalables à la reprise sur incident de BlueXP  ont été mises à jour.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Conditions préalables à la reprise d'activité BlueXP"].



== 15 mai 2024

Cette version de reprise d'activité de BlueXP inclut les mises à jour suivantes :



=== Réplication des charges de travail VMware du stockage sur site vers le stockage sur site

Il est maintenant disponible en tant que fonctionnalité de disponibilité générale. Auparavant, il s'agissait d'un aperçu technologique avec des fonctionnalités limitées.



=== Mises à jour des licences

Avec la solution de reprise après incident BlueXP , vous pouvez vous inscrire à un essai gratuit de 90 jours, acheter un abonnement PAYGO avec Amazon Marketplace ou BYOL (Bring Your Own License), un fichier de licence NetApp que vous obtenez auprès de votre ingénieur commercial NetApp ou auprès du site de support NetApp (NSS).

Pour plus d'informations sur la configuration des licences pour la reprise d'activité BlueXP, reportez-vous à la section link:../get-started/dr-licensing.html["Configuration des licences"].

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].



== 5 mars 2024

Il s'agit de la version General Availability de BlueXP Disaster Recovery, qui comprend les mises à jour suivantes.



=== Mises à jour des licences

Avec BlueXP  Disaster Recovery, vous pouvez vous inscrire à un essai gratuit de 90 jours ou BYOL (Bring Your Own License), un fichier de licence NetApp que vous obtenez auprès de votre ingénieur commercial NetApp Vous pouvez utiliser le numéro de série de licence pour activer la fonction BYOL dans le portefeuille digital BlueXP. Les frais de reprise d'activité BlueXP sont calculés en fonction de la capacité provisionnée des datastores.

Pour plus d'informations sur la configuration des licences pour la reprise d'activité BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configuration des licences"].

Pour plus d'informations sur la gestion des licences pour *tous* services BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Gérez les licences de tous les services BlueXP"^].



=== Modifier les horaires

Avec cette version, vous pouvez désormais définir des plannings de test de conformité et de basculement afin de vous assurer qu'ils fonctionneront correctement si vous en avez besoin.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créez le plan de réplication"].



== 1er février 2024

Cette version de préversion de la reprise d'activité de BlueXP inclut les mises à jour suivantes :



=== Amélioration du réseau

Avec cette version, vous pouvez désormais redimensionner les valeurs du CPU et de la RAM de la machine virtuelle. Vous pouvez également sélectionner une adresse IP statique ou DHCP réseau pour la machine virtuelle.

* DHCP : si vous choisissez cette option, vous fournissez les informations d'identification de la machine virtuelle.
* IP statique : vous pouvez sélectionner les mêmes informations ou des informations différentes à partir de la machine virtuelle source. Si vous choisissez la même chose que la source, vous n'avez pas besoin d'entrer les informations d'identification. En revanche, si vous choisissez d'utiliser des informations différentes de la source, vous pouvez fournir les informations d'identification, l'adresse IP, le masque de sous-réseau, le DNS et la passerelle.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Scripts personnalisés

Peut désormais être inclus en tant que processus post-basculement. Avec les scripts personnalisés, la reprise d'activité BlueXP peut exécuter votre script après un processus de basculement. Par exemple, vous pouvez utiliser un script personnalisé pour reprendre toutes les transactions de base de données une fois le basculement terminé.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculez vers un site distant"].



=== Relation SnapMirror

Il est désormais possible de créer une relation SnapMirror pendant le développement du plan de réplication. Auparavant, vous deviez créer la relation en dehors de la reprise d'activité BlueXP.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Groupes de cohérence

Lorsque vous créez un plan de réplication, vous pouvez inclure des machines virtuelles provenant de différents volumes et SVM. La reprise d'activité BlueXP crée une copie Snapshot de groupe de cohérence en incluant tous les volumes et en mettant à jour tous les sites secondaires.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Option de délai de mise sous tension de la machine virtuelle

Lorsque vous créez un plan de réplication, vous pouvez ajouter des machines virtuelles à un groupe de ressources. Avec Resource Groups, vous pouvez définir un délai sur chaque machine virtuelle afin qu'elle se met sous tension en séquence différée.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Copies Snapshot cohérentes au niveau des applications

Vous pouvez spécifier de créer des copies Snapshot cohérentes au niveau des applications. Le service arrête l'application, puis prend un Snapshot pour obtenir un état cohérent de l'application.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



== 11 janvier 2024

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes :



=== Tableau de bord plus rapide

Cette version vous permet d'accéder plus rapidement aux informations d'autres pages du tableau de bord.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Découvrez la reprise d'activité BlueXP"].



== 20 octobre 2023

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes.



=== Protégez les workloads VMware sur site basés sur NFS

Désormais, avec la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS contre les incidents vers un autre environnement VMware sur site et NFS en plus du cloud public. La reprise d'activité BlueXP orchestre l'achèvement des plans de reprise d'activité.


NOTE: Avec cette offre de prévisualisation, NetApp se réserve le droit de modifier les détails, le contenu et le calendrier de l'offre avant la disponibilité générale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].



== 27 septembre 2023

Cette version préliminaire de la reprise d'activité de BlueXP inclut les mises à jour suivantes :



=== Mises à jour du tableau de bord

Vous pouvez maintenant cliquer sur les options du tableau de bord, ce qui vous permet de passer rapidement en revue les informations. De plus, le tableau de bord affiche désormais l'état des basculements et des migrations.

Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Consultez l'état de vos plans de reprise sur incident dans le tableau de bord"].



=== Mises à jour du plan de réplication

* *RPO* : vous pouvez maintenant saisir l'objectif de point de récupération (RPO) et le nombre de rétention dans la section datastores du plan de réplication. Indique la quantité de données qui doit exister et qui n'est pas antérieure à l'heure définie. Si, par exemple, vous le configurez à 5 minutes, le système peut perdre jusqu'à 5 minutes de données en cas d'incident sans affecter les besoins stratégiques de l'entreprise.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Améliorations de la mise en réseau* : lorsque vous mappez la mise en réseau entre les emplacements source et cible dans la section machines virtuelles du plan de réplication, BlueXP Disaster Recovery propose désormais deux options : DHCP ou IP statique. Auparavant, seul DHCP était pris en charge. Pour les adresses IP statiques, vous configurez le sous-réseau, la passerelle et les serveurs DNS. En outre, vous pouvez maintenant saisir des informations d'identification pour les machines virtuelles.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].

* *Modifier les plannings* : vous pouvez maintenant mettre à jour les plannings de plans de réplication.
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les ressources"].

* *SnapMirror automation* : lors de la création du plan de réplication dans cette version, vous pouvez définir la relation SnapMirror entre les volumes source et cible dans l'une des configurations suivantes :
+
** 1 à 1
** 1 à plusieurs dans une architecture en éventail
** De plusieurs à 1 en tant que groupe de cohérence
** De plusieurs à plusieurs
+
Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].







== 1er août 2023



=== Aperçu de la reprise d'activité BlueXP 

La préversion de la reprise d'activité BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. À l'aide de la préversion de la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS exécutant le stockage NetApp vers VMware Cloud (VMC) sur AWS avec Amazon FSX pour ONTAP.


NOTE: Avec cette offre de prévisualisation, NetApp se réserve le droit de modifier les détails, le contenu et le calendrier de l'offre avant la disponibilité générale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].

Cette version comprend les mises à jour suivantes :



=== Mise à jour des groupes de ressources pour l'ordre de démarrage

Lorsque vous créez un plan de reprise après incident ou de réplication, vous pouvez ajouter des machines virtuelles à des groupes de ressources fonctionnelles. Les groupes de ressources vous permettent de placer un ensemble de machines virtuelles dépendantes dans des groupes logiques qui répondent à vos besoins. Par exemple, les groupes peuvent contenir un ordre de démarrage qui peut être exécuté lors de la restauration. Avec cette version, chaque groupe de ressources peut inclure une ou plusieurs machines virtuelles. Les machines virtuelles s'allume en fonction de l'ordre dans lequel vous les incluez dans le plan. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Sélectionnez les applications à répliquer et attribuez des groupes de ressources"].



=== Vérification de la réplication

Après avoir créé le plan de reprise sur incident ou de réplication, identifiez la récurrence dans l'assistant et lancez une réplication vers un site de reprise sur incident, la reprise sur incident BlueXP  vérifie toutes les 30 minutes que la réplication se produit réellement conformément au plan. Vous pouvez surveiller la progression dans la page moniteur des tâches. Reportez-vous à la  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Réplication d'applications vers un autre site"].



=== Le plan de réplication affiche les planifications de transfert pour les objectifs de point de récupération (RPO)

Lorsque vous créez un plan de réplication ou de reprise d'activité, vous sélectionnez les machines virtuelles. Dans cette version, vous pouvez désormais afficher la SnapMirror associée à chacun des volumes associés au datastore ou à la machine virtuelle. Vous pouvez également consulter les planifications de transfert RPO associées à la planification SnapMirror. L'objectif de point de récupération vous permet de déterminer si votre planification de sauvegarde est suffisante pour permettre une reprise après incident. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



=== Mise à jour de Job Monitor

La page surveillance des travaux comprend désormais une option Actualiser qui vous permet d'obtenir un état à jour des opérations. Reportez-vous à la  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Surveiller les tâches de reprise après incident"].



== 18 mai 2023

Il s'agit de la version initiale de la reprise d'activité de BlueXP.



=== Service de reprise après incident basé sur le cloud

BlueXP est un service de reprise après incident basé dans le cloud qui automatise les workflows de reprise après incident. À l'aide de la préversion de la reprise d'activité BlueXP, vous pouvez protéger vos workloads VMware sur site basés sur NFS exécutant le stockage NetApp vers VMware Cloud (VMC) sur AWS avec Amazon FSX pour ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["En savoir plus sur la reprise d'activité BlueXP"].
